name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      
name: Clonar el repositorio
      uses: actions/checkout@v3

      
name: Configurar Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Cambia esto según tu versión de Java
        distribution: 'temurin'

      
name: Dar permisos a gradlew
      run: chmod +x gradlew

      
name: Compilar el proyecto
      run: ./gradlew build

      
name: Ejecutar los tests
      run: ./gradlew test
